---
version: "3"

vars:
  CHANNEL: '{{ default "stable" .CHANNEL }}'

tasks:
  default:
    silent: true
    cmds:
      - task -l

  build:
    desc: |-
      task APP=<app> CHANNEL=<channel> build
    vars:
      MULTIPLATFORM: '{{ default "false" .MULTIPLATFORM }}'
    cmds:
      - >-
        podman build
        --build-arg CHANNEL={{.CHANNEL}}
        --build-arg VERSION=$(bash ./.github/scripts/upstream.sh "{{.APP}}" "{{.CHANNEL}}")
        {{if eq .MULTIPLATFORM "true"}}
        --platform $(jq -r '.channels[] | select(.name=="{{.CHANNEL}}").platforms | join(",")' ./apps/{{.APP}}/metadata.json)
        {{else}}
        --platform "linux/$(uname -m | sed 's/x86_64/amd64/')"
        {{end}}
        -f ./apps/{{.APP}}/Dockerfile
        --manifest {{.APP}}:{{.CHANNEL}}
        .
      # - >-
      #   docker buildx build --progress=plain --load
      #   -t {{.APP}}:{{.CHANNEL}}
      #   --build-arg CHANNEL={{.CHANNEL}}
      #   --build-arg VERSION=$(bash ./.github/scripts/upstream.sh "{{.APP}}" "{{.CHANNEL}}")
      #   -f ./apps/{{.APP}}/Dockerfile .

  test:
    desc: |-
      task APP=<app> CHANNEL=<channel> BASE=<true/false> test
    cmds:
      - task: download-goss
      - task: download-cue
      - >-
        ./.cue/cue vet --schema '#Spec' ./apps/{{.APP}}/metadata.json metadata.rules.cue
      - task: build
      - >-
        ./.goss/dgoss run $(jq -r '.channels[] | select(.name=="{{.CHANNEL}}").tests.dgoss_args//""' ./apps/{{.APP}}/metadata.json) {{.APP}}:{{.CHANNEL}} {{if eq .BASE "true"}}tail  -f /dev/null{{end}}
    env:
      CONTAINER_RUNTIME: podman
      GOSS_PATH: ./.goss/goss
      GOSS_OPTS: --retry-timeout 15s --color --format documentation
      GOSS_SLEEP: 2
      GOSS_FILE: ./apps/{{.APP}}/ci/goss.yaml
      GOSS_FILES_STRATEGY: cp

  download-goss:
    silent: true
    vars:
      # renovate: datasource=github-releases depName=aelsabbahy/goss
      GOSS_VERSION: 0.4.7
    cmds:
      - mkdir -p ./.goss
      - curl -fsSL -o ./.goss/goss https://github.com/aelsabbahy/goss/releases/download/{{.GOSS_VERSION}}/goss-linux-amd64
      - chmod +x ./.goss/goss
      - curl -fsSL -o ./.goss/dgoss https://raw.githubusercontent.com/aelsabbahy/goss/{{.GOSS_VERSION}}/extras/dgoss/dgoss
      - chmod +x ./.goss/dgoss
    status:
      - test -f ./.goss/goss
      - test -f ./.goss/dgoss

  download-cue:
    silent: true
    vars:
      # renovate: datasource=github-releases depName=cue-lang/cue
      CUE_VERSION: 0.7.0
    cmds:
      - mkdir -p ./.cue
      - curl -fsSL -o ./.cue/cue.tar.gz https://github.com/cue-lang/cue/releases/download/{{.CUE_VERSION}}/cue_{{.CUE_VERSION}}_linux_amd64.tar.gz
      - tar -xC ./.cue -f ./.cue/cue.tar.gz
      - chmod +x ./.cue/cue
    status:
      - test -f ./.cue/cue
