---
name: "Action: Image Build"

on:
  workflow_call:
    inputs:
      imagesToBuild:
        description: |-
          Pass a json string with the images and channels to build. e.g.:
            [
              {
                "app": "sonarr",
                "channel": "main"
              },
              {
                "app": "sonarr",
                "channel": "develop"
              }
            ]
        required: false
        type: string
        default: ''

      pushImages:
        required: false
        default: 'false'
        type: string

      updateMetadata:
        required: false
        default: 'false'
        type: string

env:
  IMAGE_REGISTRY_GHCR: ghcr.io

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-22.04
    if: inputs.imagesToBuild != '' && inputs.imagesToBuild != '[]'
    strategy:
      matrix:
        image: ["${{ fromJson(inputs.imagesToBuild) }}"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup workflow Variables
        id: vars
        shell: bash
        run: |-
          container_base=$(jq '.base' ./apps/${{ matrix.image.app }}/metadata.json)
          echo "::set-output name=chan_build_date::$(date --rfc-3339=seconds --utc)"

          chan_config=$(jq --arg chan "${{ matrix.image.channel }}" '(.channels | .[] | select(.name == $chan))' ./apps/${{ matrix.image.app }}/metadata.json)
          chan_stable=$(jq --raw-output '.stable' <<< "${chan_config}")

          chan_platforms=$(jq --raw-output '.platforms | join(",")' <<< "${chan_config}") && \
              echo "::set-output name=chan_platforms::${chan_platforms}"
          chan_tests_enabled=$(jq --raw-output '.tests.enabled' <<< "${chan_config}") && \
              echo "::set-output name=chan_tests_enabled::${chan_tests_enabled}"
          chan_tests_type=$(jq --raw-output '.tests.type' <<< "${chan_config}") && \
              echo "::set-output name=chan_tests_type::${chan_tests_type}"
          chan_dgoss_args=$(jq --raw-output '.tests.dgoss_args' <<< "${chan_config}") && \
              echo "::set-output name=chan_dgoss_args::${chan_dgoss_args}"

          chan_upstream_version=$(bash ./.github/scripts/upstream.sh "${{ matrix.image.app }}" "${{ matrix.image.channel }}") && \
              echo "::set-output name=chan_upstream_version::${chan_upstream_version}"

          if [[ "${chan_tests_enabled}" == true && "${chan_tests_type}" == "cli" ]]; then
              echo "::set-output name=chan_goss_args::tail -f /dev/null"
          fi

          if [[ "${container_base}" == true ]]; then
              echo "::set-output name=chan_label_type::org.opencontainers.image.base"
          else
              echo "::set-output name=chan_label_type::org.opencontainers.image"
          fi

          if test -f "./apps/${{ matrix.image.app }}/${{ matrix.image.channel }}/Dockerfile"; then
              echo "::set-output name=chan_dockerfile::./apps/${{ matrix.image.app }}/${{ matrix.image.channel }}/Dockerfile"
              echo "::set-output name=chan_goss_config::./apps/${{ matrix.image.app }}/${{ matrix.image.channel }}/goss.yaml"
          else
              echo "::set-output name=chan_dockerfile::./apps/${{ matrix.image.app }}/Dockerfile"
              echo "::set-output name=chan_goss_config::./apps/${{ matrix.image.app }}/ci/goss.yaml"
          fi

          if [[ "${chan_stable}" == true ]]; then
              echo "::set-output name=chan_tag_rolling::${{ matrix.image.app }}:rolling"
              echo "::set-output name=chan_tag_version::${{ matrix.image.app }}:${chan_upstream_version}"
          else
              echo "::set-output name=chan_tag_rolling::${{ matrix.image.app }}-${{ matrix.image.channel }}:rolling"
              echo "::set-output name=chan_tag_version::${{ matrix.image.app }}-${{ matrix.image.channel }}:${chan_upstream_version}"
          fi

      - name: Setup cli tools
        shell: bash
        run: sudo apt-get install moreutils jo

      - name: Setup CUE
        uses: cue-lang/setup-cue@v1.0.0-alpha.2

      - name: Setup Goss
        if: ${{ steps.vars.outputs.chan_tests_enabled == 'true' }}
        uses: e1himself/goss-installation-action@v1.2.1
        with:
          # renovate: datasource=github-releases depName=aelsabbahy/goss
          version: 0.4.4
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Validate image metadata
        shell: bash
        run: |-
          cue vet --schema '#Spec' ./apps/${{ matrix.image.app }}/metadata.json ./metadata.rules.cue

      - name: Build all platforms
        id: build_image
        uses: redhat-actions/buildah-build@v2.12
        with:
          build-args: |-
            VERSION=${{ steps.vars.outputs.chan_upstream_version }}
            CHANNEL=${{ matrix.image.channel }}
          platforms: ${{ steps.vars.outputs.chan_platforms }}
          context: .
          containerfiles: |
            ${{ steps.vars.outputs.chan_dockerfile }}
          tags: |-
            ${{ env.IMAGE_REGISTRY_GHCR }}/${{ github.repository_owner }}/${{ steps.vars.outputs.chan_tag_rolling }}
            ${{ env.IMAGE_REGISTRY_GHCR }}/${{ github.repository_owner }}/${{ steps.vars.outputs.chan_tag_version }}
          labels: |-
            ${{ steps.vars.outputs.chan_label_type }}.created="${{ steps.vars.outputs.chan_build_date }}"
            ${{ steps.vars.outputs.chan_label_type }}.title="${{ matrix.image.app }} (${{ matrix.image.channel }})"
            ${{ steps.vars.outputs.chan_label_type }}.version="${{ steps.vars.outputs.chan_upstream_version }}"
            ${{ steps.vars.outputs.chan_label_type }}.authors="Angel Nunez Mencias <git@angelnu.com>"
            ${{ steps.vars.outputs.chan_label_type }}.url="https://github.com/${{ github.repository_owner }}/apps/${{ matrix.image.app }}"
            ${{ steps.vars.outputs.chan_label_type }}.build.url="https://github.com/${{ github.repository_owner }}/actions/runs/${{ github.run_id }}"
            ${{ steps.vars.outputs.chan_label_type }}.documentation="https://github.com/${{ github.repository_owner }}/apps/${{ matrix.image.app }}/README.md"
            ${{ steps.vars.outputs.chan_label_type }}.revision="${{ github.sha }}"
            ${{ steps.vars.outputs.chan_label_type }}.source https://github.com/OWNER/REPO

      - name: Run Goss tests
        id: dgoss
        if: ${{ steps.vars.outputs.chan_tests_enabled == 'true' }}
        shell: bash
        env:
          CONTAINER_RUNTIME: podman
          GOSS_FILE: ${{ steps.vars.outputs.chan_goss_config }}
          GOSS_OPTS: |-
            --retry-timeout 60s --color --format documentation
          GOSS_SLEEP: 2
        run: >
          dgoss run ${{ steps.vars.outputs.chan_dgoss_args }} ${{ env.IMAGE_REGISTRY_GHCR }}/${{ github.repository_owner }}/${{ steps.vars.outputs.chan_tag_rolling }} ${{ steps.vars.outputs.chan_goss_args }}

      - name: Push To GHCR
        id: push_to_ghcr
        if: ${{ inputs.pushImages == 'true' }}
        uses: redhat-actions/push-to-registry@v2.8
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY_GHCR }}/${{ env.IMAGE_NAMESPACE }}
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Build successful
        id: build-success
        if: ${{ always() && steps.build_image.outcome == 'success' && steps.dgoss.outcome == 'success' && (steps.push_to_ghcr.outcome == 'success' || steps.push_to_ghcr.outcome == 'skipped') }}
        run: |-
          echo "::set-output name=message::🎉 ${{ matrix.image.app }}-${{ matrix.image.channel }} (${{ steps.vars.outputs.chan_upstream_version }})"
          echo "::set-output name=color::0x00FF00"

      - name: Build failed
        id: build-failed
        if: ${{ always() && (steps.build_image.outcome == 'failure' || steps.dgoss.outcome == 'failure' || steps.push_to_ghcr.outcome == 'failure') }}
        run: |-
          echo "::set-output name=message::💥 ${{ matrix.image.app }}-${{ matrix.image.channel }} (${{ steps.vars.outputs.chan_upstream_version }})"
          echo "::set-output name=color::0xFF0000"

  # Summarize matrix https://github.community/t/status-check-for-a-matrix-jobs/127354/7
  build_success:
    name: Build matrix success
    runs-on: ubuntu-22.04
    needs:
      - build-and-test
    if: ${{ always() }}
    steps:
      - name: Check build matrix status
        if: ${{ (inputs.imagesToBuild != '' && inputs.imagesToBuild != '[]') && (needs.build-and-test.result != 'success') }}
        run: exit 1
